### ISSUE TITLE
Wrong layout behavoir on content size change

### ISSUE THREAD

**Issue by JaRoMasterDev** [susonthapa/react-native-global-modal#1]
When the content of the model changes it's size, it takes the modal CHILD_ANIM_DURATION ms to start and again LAYOUT_ANIM_DURATION ms to finish changing the size of the modal. I think the model should, in this case, not wait CHILD_ANIM_DURATION before changing it's size.

    <Animated.View
      style={styles.modalView}
      layout={Layout.delay(CHILD_ANIM_DURATION).duration(
        LAYOUT_ANIM_DURATION,
      )}>

**Comment by susonthapa** [comment]
Hey @JaRoMasterDev, Do you have a video of this?

**Comment by JaRoMasterDev** [comment]
Hey @susonthapa, Here's a video of that bug

https://github.com/susonthapa/react-native-global-modal/assets/89219016/3f49ca87-bb8e-467e-99b3-b7dd90ec4271

**Comment by susonthapa** [comment]
Hey @JaRoMasterDev Can you test if #2 fixes your issue? Reanimated doesn't yet support changing [the animation](https://github.com/software-mansion/react-native-reanimated/issues/3662) parameters once the view is mounted. I added some workaround for it. Let me know if that fixes your issue.

**Comment by JaRoMasterDev** [comment]
That seems to be a great workaround!
But I think there is still a small animation bug when my modal gets smaller again. The buttons seem to be flashing to a wrong position for a split of a second. I attached a video which hopefully shows what I mean.

https://github.com/susonthapa/react-native-global-modal/assets/89219016/9d5f8e5c-b454-48a7-8ac3-b92f082f4bdc

**Comment by susonthapa** [comment]
> That seems to be a great workaround! But I think there is still a small animation bug when my modal gets smaller again. The buttons seem to be flashing to a wrong position for a split of a second. I attached a video which hopefully shows what I mean.
> 
>  Screen_Recording_20231105_205038_MyGainplan.mp4

I think this is what's happening. When you close the Advanced Settings, the layout happens immediately and moves the buttons to their correct position.
<img width="308" alt="image" src="https://github.com/susonthapa/react-native-global-modal/assets/33973551/d83597ed-c210-4f4c-87ea-38573900f8e8">

However, the Modal hasn't been fully resized so they appear at the top. During the next layout, the Modal gets resized and they are moved down to their correct position.
<img width="302" alt="image" src="https://github.com/susonthapa/react-native-global-modal/assets/33973551/85033575-58d2-4aba-86d5-9764d8d37aa8">

Can you please check if this happens with the React Native Modal or not? This is an interesting issue. I will take a look at it when I'm free. Feel free to look into this yourself if you have time.

**Comment by JaRoMasterDev** [comment]
I believe the problem is that the disabledLayoutAnimation has a duration of 1. I think due to this it takes the animation 1 frame to complete, in which the container is still the old size after the child already shrank... I am currently looking for a workaround, but I don't have much experience with react-native-reanimated

**Comment by JaRoMasterDev** [comment]
I think I found a workoaround for this bug. When using a duration of -1 on the disabledLayoutAnimation, the animation get's executed instantly without this wrong frame.
`const disabledLayoutAnimation = new Layout().duration(-1).build();`

**Comment by susonthapa** [comment]
> I think I found a workoaround for this bug. When using a duration of -1 on the disabledLayoutAnimation, the animation get's executed instantly without this wrong frame. `const disabledLayoutAnimation = new Layout().duration(-1).build();`

Awesome, didn't think about -1. I tried with 0 and it just used a default duration.
